export const DEFAULT_EMOTIONS = [
	{
		id: 1,
		name: "Joy",
		color: "#c1e08d",
		emotions: [
			"joyful",
			"content",
			"pleased",
			"satisfied",
			"happy",
			"amused",
			"delighted",
			"cheerful",
			"jovial",
			"blissful",
			"proud",
			"triumphant",
			"optimistic",
			"eager",
			"hopeful",
			"enthusiastic",
			"excited",
			"euphoric",
			"enchanted",
		],
	},
	{
		id: 2,
		name: "Love",
		color: "#e8c3da",
		emotions: [
			"loving",
			"romantic",
			"affectionate",
			"passionate",
			"attracted",
			"sentimental",
			"compassionate",
			"satisfied",
			"peaceful",
			"relieved",
		],
	},
	{
		id: 3,
		name: "Surprise",
		color: "#94d4d3",
		emotions: [
			"surprised",
			"shocked",
			"dismayed",
			"confused",
			"disillusioned",
			"perplexed",
			"amazed",
			"astonished",
			"moved",
			"touched",
		],
	},
	{
		id: 4,
		name: "Anger",
		color: "#b84444",
		emotions: [
			"angry",
			"enraged",
			"hateful",
			"hostile",
			"agitated",
			"frustrated",
			"irritated",
			"annoyed",
			"aggravated",
			"envious",
			"jealous",
			"disgusted",
			"contemptful",
		],
	},
	{
		id: 5,
		name: "Sadness",
		color: "#4e72a3",
		emotions: [
			"sad",
			"hurt",
			"agonizing",
			"depressed",
			"sorrowful",
			"disappointed",
			"dismayed",
			"displeased",
			"shameful",
			"regretful",
			"guilty",
			"neglected",
			"isolated",
			"lonely",
			"despaired",
			"grieving",
			"powerless",
		],
	},
	{
		id: 6,
		name: "Fear",
		color: "#dbab4b",
		emotions: [
			"fearful",
			"scared",
			"helpless",
			"frightened",
			"panicking",
			"hystetical",
			"insecure",
			"inferior",
			"inadequate",
			"nervous",
			"anxious",
			"worried",
			"dreadful",
			"mortified",
		],
	},
	{
		id: 7,
		name: "Attitude",
		color: "#a24cdc",
		emotions: [
			"Abrasive",
			"Accepting",
			"Adventurous",
			"Affectionate",
			"Aggressive",
			"Agreeable",
			"Aloof",
			"Ambivalent",
			"Angry",
			"Angsty",
			"Annoyed",
			"Antagonistic",
			"Antisocial",
			"Anxious or Worried",
			"Apathetic",
			"Arrogant",
			"Assertive",
			"Avoidant",
			"Awestruck",
			"Belligerent",
			"Benevolent",
			"Biased",
			"Bigoted",
			"Brave or Courageous",
			"Broadminded",
			"Buoyant",
			"Callous",
			"Calm",
			"Caring",
			"Cheerful",
			"Cheerless",
			"Closed-minded",
			"Cold / Cold-hearted",
			"Commanding",
			"Competitive",
			"Conceited",
			"Concerned",
			"Conciliatory",
			"Condescending",
			"Confident",
			"Contrarian",
			"Critical",
			"Cynical",
			"Daring",
			"Dark",
			"Defeatist",
			"Defensive",
			"Depressed",
			"Detached",
			"Determined",
			"Diplomatic",
			"Disdainful",
			"Disgusted",
			"Disrespectful",
			"Distrustful",
			"Empathetic",
			"Energetic",
			"Enterprising",
			"Enthusiastic",
			"Expectant",
			"Fearful",
			"Festive",
			"Flexible",
			"Flippant",
			"Forgiving",
			"Fretful",
			"Friendly",
			"Frustrated",
			"Furtive",
			"Gloomy",
			"Glum",
			"Gratitude",
			"Grim",
			"Grounded",
			"Hesitant",
			"Hopeful",
			"Hopeless or Despairing",
			"Hostile or Inhospitable",
			"Humble",
			"Impartial",
			"Impatient",
			"Imperious",
			"Imperturbable",
			"Indifferent (to others)",
			"Indignant",
			"Inquisitive",
			"Insecure",
			"Interested",
			"Intolerant",
			"Intransigent",
			"Irresponsible",
			"Jealous",
			"Joyful / Joyous",
			"Judgmental",
			"Lazy",
			"Liberal or Generous",
			"Lighthearted",
			"Lively",
			"Loving",
			"Malevolent",
			"Maternal or Maternalistic",
			"Mean-spirited or Malicious",
			"Miserable",
			"Moralistic",
			"Morose",
			"Negative",
			"Neutral",
			"Nihilistic",
			"No-Nonsense",
			"Objective",
			"Obnoxious",
			"Obsequious",
			"Open / Open-minded",
			"Optimistic",
			"Overconfident",
			"Parsimonious",
			"Passionate",
			"Passive",
			"Paternal or Paternalistic",
			"Patient",
			"Patronizing",
			"Pessimistic",
			"Polite",
			"Positive",
			"Practical",
			"Pragmatic",
			"Professional",
			"Querulous",
			"Rational or Reasonable",
			"Recalcitrant",
			"Reluctant",
			"Resentful or Bitter",
			"Reserved",
			"Resilient",
			"Resistant",
			"Respectful",
			"Responsible",
			"Reticent",
			"Reverent",
			"Sardonic (sharp/sarcastic)",
			"Secretive",
			"Self-assured",
			"Self-effacing",
			"Selfish",
			"Selfless",
			"Self-righteous",
			"Serious",
			"Skeptical",
			"Sneaky",
			"Snobby / Snobbish",
			"Solemn",
			"Somber",
			"Sorrowful",
			"Spiteful",
			"Stubborn or Obstinate or Inflexible",
			"Suspicious",
			"Sympathetic",
			"Thoughtful",
			"Timid or Timorous",
			"Tireless or Indefatigable",
			"Tolerant",
			"Traumatized",
			"Trusting",
			"Unaffected",
			"Unassuming",
			"Unbiased or Impartial",
			"Understanding",
			"Unfriendly or Unsociable",
			"Unprofessional",
			"Unwavering or Immovable",
			"Vigilant or Hypervigilant",
			"Volatile or Explosive",
			"Warm or Compassionate",
			"Whimsical",
			"Willing",
			"Withdrawn",
		],
	},
];
